src/config/routes.rb
Rails.application.routes.draw do
  resources :tv_shows do
    member do
      get :export, :defaults => { :format => :yaml }
    end

    collection do
      get :import
      post :perform_import
    end

    resources :episodes, only: [:index, :show]
    resources :seasons do
      resources :discs do
        resources :episodes, only: [:index, :show]
      end
      resources :episodes do
        resources :episode_discs
      end
    end

    resources :collections do
      resources :discs, only: [:index, :show]

      member do
        get :associate_disc
        post :perform_associate_disc
      end
    end
  end

  root :to => 'tv_shows#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resource :users, only: [:show] do
    resources :api_keys
  end

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api, only: [:index, :show]

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :tv_shows do
        collection do
          get :import
        end

        resources :episodes, only: [:index, :show]
        resources :seasons do
          resources :discs do
            resources :episodes, only: [:index, :show]
          end
          resources :episodes do
            resources :episode_discs
          end
        end

        resources :collections do
          resources :discs, only: [:index, :show]

          member do
            post :associate_disc
          end
        end
      end
      resources :discs, only: [:index, :show]
    end
  end
end

src/app/models/season.rb
class Season < ActiveRecord::Base
  include Filterable

  audited

  belongs_to :user
  belongs_to :tv_show

  has_many :episodes, dependent: :destroy
  has_many :discs, dependent: :destroy


  validates :number, presence: true
  validates :tv_show_id, presence: true

  validates_uniqueness_of :number, scope: :tv_show_id


  scope :tv_show, -> (tv_show) { where('tv_show_id = ?', TvShow.find_by_name(tv_show).id) }


  def to_s
    self.number.to_s
  end

  def to_hash
    {
        number: self.number,
        tvdb_id: self.tvdb_id,
        discs: self.discs.map {|disc| disc.to_hash}
    }
  end

  def to_param
    number.to_s
  end
end

src/app/controllers/api/v1/seasons_controller.rb
class API::V1::SeasonsController < API::APIBaseController
  #load_and_authorize_resource
  before_action :set_season, only: [:show, :update, :destroy]
  before_action :set_tv_show, only: [:create]

  # GET /seasons
  def index
    if params[:tv_show_id]
      @seasons = TvShow.friendly.find(params[:tv_show_id]).seasons
    else
      @seasons = Season.filter(params.slice(:tv_show))
    end
  end

  # GET /seasons/1
  def show
  end

  # POST /seasons.json
  def create
    @season = @tv_show.seasons.new(season_params)
    authorize! :create, @season

    respond_to do |format|
      if @season.save
        format.json { render :show, status: :created, location: tv_show_season_path(@season.tv_show, @season) }
      else
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1.json
  def update
    authorize! :update, @season

    respond_to do |format|
      if @season.update(season_params)
        format.json { render :show, status: :ok, location: tv_show_season_path(@season.tv_show, @season) }
      else
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1.json
  def destroy
    authorize! :destroy, @season
    @season.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_season
    @season = Season.find_by_tv_show_id_and_number(TvShow.friendly.find(params[:tv_show_id]), params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def season_params
    params.require(:season).permit(:number, :tvdb_id).merge(:audit_comment => "api_key_id=#{current_api_key.id}")
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_tv_show
    @tv_show = TvShow.friendly.find(params[:tv_show_id])
  end
end

src/app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  #load_and_authorize_resource
  before_action :set_season, only: [:show, :edit, :update, :destroy]
  before_action :set_tv_show, only: [:index, :new, :create]

  # GET /seasons
  def index
    @seasons = @tv_show.seasons
  end

  # GET /seasons/1
  def show
  end

  # GET /seasons/new
  def new
    @season = @tv_show.seasons.new
    authorize! :new, @season
  end

  # GET /seasons/1/edit
  def edit
    authorize! :edit, @season
  end

  # POST /seasons
  def create
    @season = @tv_show.seasons.new(season_params)
    authorize! :create, @season

    respond_to do |format|
      if @season.save
        format.html { redirect_to [@season.tv_show, @season], notice: 'Season was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /seasons/1
  def update
    authorize! :update, @season

    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to [@season.tv_show, @season], notice: 'Season was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /seasons/1
  def destroy
    authorize! :destroy, @season
    @season.destroy

    respond_to do |format|
      format.html { redirect_to tv_show_seasons_path, notice: 'Season was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find_by_tv_show_id_and_number(TvShow.friendly.find(params[:tv_show_id]), params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:number, :tvdb_id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.friendly.find(params[:tv_show_id])
    end
end

src/app/helpers/api/v1/seasons_helper.rb
module API::V1::SeasonsHelper
end

src/app/helpers/seasons_helper.rb
module SeasonsHelper
end

src/app/views/seasons/_form.html.erb
<%= form_for([@season.tv_show, @season]) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :tvdb_id %><br>
    <%= f.number_field :tvdb_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/seasons/_season.html.erb
<tr>
  <td><%= link_to season.number, [season.tv_show, season] %></td>
  <td><%= season.tvdb_id ? link_to(season.tvdb_id, tvdb_url(season)) : nil %></td>
  <td><%= link_to season.tv_show.name, season.tv_show %></td>
  <td><%= link_to season.discs.count, tv_show_season_discs_path(season.tv_show, season) %></td>
  <td><%= link_to season.episodes.count, tv_show_season_episodes_path(season.tv_show, season) %></td>
  <td>
    <%= link_to t('general.edit'), edit_tv_show_season_path(season.tv_show, season) if can? :edit, Season %>
    <%= link_to t('general.destroy'), [season.tv_show, season], method: :delete, data: { confirm: t('general.are_you_sure')} if can? :destroy, Season %>
  </td>
</tr>

src/app/views/seasons/_seasons.html.erb
<table id='seasons_table' class='data_table'>
  <thead>
  <tr>
    <th><%= t('seasons.season_number') %></th>
    <th><%= t('seasons.tvdb_id') %></th>
    <th><%= t('tv_shows.tv_shows') %></th>
    <th><%= t('discs.discs') %></th>
    <th><%= t('episodes.episodes') %></th>
    <th><%= t('general.tables.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% seasons.each do |season| %>
      <%= render 'seasons/season', :season => season %>
  <% end %>
  </tbody>
</table>

src/app/views/seasons/edit.html.erb
<h1><%= t('general.editing') % t('seasons.season') %> - <%= @season.tv_show %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', tv_show_season_path %>

src/app/views/seasons/index.html.erb
<h1><%= t('general.listing') % t('seasons.seasons') %>
  <span class='actions'>
        <% if can? :create, Season  %>
          <%= link_to 'New', new_tv_show_season_path, :id => 'new_season_link' %>
        <% end  %>
    </span>
</h1>
<%= render 'seasons', :seasons => @seasons %>

src/app/views/seasons/new.html.erb
<h1><%= t('general.editing') % t('seasons.season') %> - <%= @season.tv_show %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', tv_show_seasons_path %>

src/app/views/seasons/show.html.erb
<h1><%= "#{@season.tv_show.name} - #{t('seasons.season')} #{@season.number}" %></h1>

<strong><%= t('seasons.tvdb_id') %>:</strong>
<%= @season.tvdb_id ? link_to(@season.tvdb_id, tvdb_url(@season)) : t('general.not_applicable') %>

<h3><%= t('discs.discs') %>
  <span class='actions'>
        <% if can? :create, Disc %>
          <%= link_to 'New', new_tv_show_season_disc_path(@season.tv_show, @season), :id => 'new_tv_show_link' %>
        <% end  %>
  </span>
</h3>
<%= render 'discs/discs', :discs => @season.discs %>
<br />
<br />
<h3><%= t('episodes.episodes') %>
  <span class='actions'>
        <% if can? :create, Episode %>
          <%= link_to 'New', new_tv_show_season_episode_path(@season.tv_show, @season), :id => 'new_tv_show_link' %>
        <% end  %>
  </span>
</h3>
<%= render 'episodes/episodes', :episodes => @season.episodes %>
<br />
<br />
<%= link_to t('general.back'), [@season.tv_show, @season] %>
<% if can?(:edit, Season) %>
    | <%= link_to 'Edit', edit_tv_show_season_path(@season.tv_show, @season) %>
<% end %>