src/config/routes.rb
Rails.application.routes.draw do
  resources :tv_shows do
    member do
      get :export, :defaults => { :format => :yaml }
    end

    collection do
      get :import
      post :perform_import
    end

    resources :episodes, only: [:index, :show]
    resources :seasons do
      resources :discs do
        resources :episodes, only: [:index, :show]
      end
      resources :episodes do
        resources :episode_discs
      end
    end

    resources :collections do
      resources :discs, only: [:index, :show]

      member do
        get :associate_disc
        post :perform_associate_disc
      end
    end
  end

  root :to => 'tv_shows#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resource :users, only: [:show] do
    resources :api_keys
  end

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api, only: [:index, :show]

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :tv_shows do
        collection do
          get :import
        end

        resources :episodes, only: [:index, :show]
        resources :seasons do
          resources :discs do
            resources :episodes, only: [:index, :show]
          end
          resources :episodes do
            resources :episode_discs
          end
        end

        resources :collections do
          resources :discs, only: [:index, :show]

          member do
            post :associate_disc
          end
        end
      end
      resources :discs, only: [:index, :show]
    end
  end
end

src/app/models/tv_show.rb
class TvShow < ActiveRecord::Base
  include Filterable
  extend FriendlyId
  friendly_id :name, use: :slugged

  audited

  belongs_to :user

  has_many :seasons, dependent: :destroy
  has_many :episodes
  has_many :discs
  has_many :collections, :dependent => :destroy

  validates :name, presence: true, uniqueness: true


  scope :starts_with, -> (name) { where('name like ?', "#{name}%")}


  IMPORT_FORMATS = [
      {
          :extentions => %w(yml yaml),
          :mime_type  => 'application/x-yaml',
          :lambda     => lambda { |file|
            YAML.load_file(file.to_s)
          }
      }
  ]

  def to_s
    self.name
  end

  def to_hash
    {
        name: self.name,
        tvdb_id: self.tvdb_id,
        language: self.language,
        seasons: self.seasons.map { |season| season.to_hash },
        collections: self.collections.map { |collection| collection.to_hash },
    }
  end

  def to_yaml_file
    file_name = File.join(EXPORTS_DIRECTORY, "#{SecureRandom.hex}_tv_show_#{self.name}.yml")

    File.open(file_name, 'w') {|f| f.write self.to_hash.to_yaml }

    file_name
  end

  def self.file_to_hash(file, format = nil)
    format ||= File.extname(file).split('.').last

    format_hash = self.get_format(format)

    if format_hash
      hash = format_hash[:lambda].call(file)
    else
      raise DiscDBExceptions::IO::UnsupportedFileFormat.new "Unsupported file format: #{format.to_s}"
    end

    hash
  end

  def self.import_from_file(file, user = User.last.id, format = nil)
    TvShow.import(TvShow.file_to_hash(file, format), user)
  end

  def self.import(tv_show_hash, user = User.last.id)
    ActiveRecord::Base.transaction do
      tv_show_hash = symbolize_keys(tv_show_hash)

      tv_show = TvShow.find_or_create_by(
          :name     => tv_show_hash[:name].lstrip.rstrip,
          :tvdb_id  => tv_show_hash[:tvdb_id],
          :language => tv_show_hash[:language]
      )
      tv_show.user = user
      tv_show.save!


      if tv_show_hash[:collections]
        tv_show_hash[:collections].each do |collection|
          collection_hash = symbolize_keys(collection)
          col = Collection.find_or_create_by!(
              :name         => collection_hash[:name].lstrip.rstrip,
              :tv_show_id   => tv_show.id,
          )
          col.description = collection_hash[:description]
          col.region_code = collection_hash[:region_code]
          col.region_name = collection_hash[:region_name]
          col.user = user
          col.save!
        end
      end

      tv_show_hash[:seasons].each do |current_season_hash|
        next unless current_season_hash
        season_hash = symbolize_keys(current_season_hash)

        season = tv_show.seasons.find_or_create_by!(
            :number   => season_hash[:number],
            :tvdb_id  => season_hash[:tvdb_id]
        )
        season.user = user
        season.save!

        episode_number = 1
        season_hash[:discs].each do |current_disc_hash|
          next unless current_disc_hash
          disc_hash = symbolize_keys(current_disc_hash)

          disc = season.discs.find_or_create_by!(
              :disc_number  => disc_hash[:disc][:disc_number],
              :tv_show      => tv_show,
              :disc_type    => disc_hash[:disc][:disc_type],
              :disc_label   => disc_hash[:disc][:disc_label]
          )
          disc.user = user
          disc.save!


          if disc_hash[:disc][:collection]
            dc = DiscCollection.find_or_create_by!(
                :collection => Collection.find_by_tv_show_id_and_name!(tv_show.id, disc_hash[:disc][:collection]),
                :disc       => disc
            )

            dc.user = user
            dc.save!
          end

          disc_hash[:episodes].each do |current_episode_hash|
            next unless current_episode_hash
            episode_hash = symbolize_keys(current_episode_hash)

            episode_resource = disc.episodes.find_or_create_by!(
                :number             => episode_hash[:number].to_i,
                :tv_show            => tv_show,
                :season             => season,
                :name               => episode_hash[:name].lstrip.rstrip,
            )
            episode_resource.makemkv_name = episode_hash[:makemkv_name] ? episode_hash[:makemkv_name].lstrip.rstrip : nil
            episode_resource.user = user
            episode_resource.save!

            if episode_hash[:order]
              ed = EpisodeDisc.find_or_create_by!(
                  :episode    => episode_resource,
                  :disc       => disc
              )

              ed.disc_order = episode_hash[:order]
              ed.user       = user
              ed.save!

              episode_discs = EpisodeDisc.where(:disc_id => disc.id, :disc_order => episode_hash[:order])
              if episode_discs.count > 1
                # Has Combined Episodes
                episode_discs.each do |episode_disc|
                  episode_disc.combined_episodes = true
                  episode_disc.save!
                end
              end
            end

            episode_number = episode_number+1
          end
        end
      end
    end
  end

  def self.symbolize_keys(hash)
    hash.inject({}){|result, (key, value)|
      new_key = case key
                  when String then key.to_sym
                  else key
                end
      new_value = case value
                    when Hash then symbolize_keys(value)
                    else value
                  end
      result[new_key] = new_value
      result
    }
  end

  private
  def self.get_format(format_extension)
    format = nil

    IMPORT_FORMATS.each do |import_format|
      format = import_format if import_format[:extentions].include?(format_extension.to_s)
    end

    format
  end
end

src/app/controllers/api/v1/tv_shows_controller.rb
class API::V1::TvShowsController < API::APIBaseController
  load_and_authorize_resource :find_by => :slug
  before_action :set_tv_show, only: [:show, :update, :destroy]
  before_action :set_user, only: [:create]

  # GET /tv_shows
  def index
    @tv_shows = TvShow.filter(params.slice(:starts_with))
  end

  # GET /tv_shows/1
  def show
  end

  # POST /tv_shows.json
  def create
    @tv_show = @user.tv_shows.new(tv_show_params)

    respond_to do |format|
      if @tv_show.save
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1.json
  def destroy
    @tv_show.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tv_show
    @tv_show = TvShow.friendly.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tv_show_params
    params.require(:tv_show).permit(:name, :tvdb_id, :language).merge(:audit_comment => "api_key_id=#{current_api_key.id}")
  end
end

src/app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  load_and_authorize_resource :find_by => :slug
  before_action :set_tv_show, only: [:show, :edit, :update, :destroy, :export]

  # GET /tv_shows
  def index
    @tv_shows = TvShow.all
  end

  # GET /tv_shows/1
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
  end

  # GET /tv_shows/1/edit
  def edit
  end

  # POST /tv_shows
  def create
    @tv_show = TvShow.new(tv_show_params)

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tv_shows/1
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tv_shows/1
  def destroy
    @tv_show.destroy
    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: 'Tv show was successfully destroyed.' }
    end
  end

  # GET /tv_shows/1/export
  def export
    authorize! :export, current_user

    respond_to do |format|
      format.yaml {
        file_name = @tv_show.to_yaml_file

        response.headers['Content-Length'] = File.stat(file_name).size.to_s
        send_file file_name, type: 'application/x-yaml'
      }
    end
  end

  # GET /tv_shows/import
  def import
  end

  # POST /tv_shows/perform_import
  def perform_import
    uploaded_io = params[:file]
    save_path = Rails.root.join('tmp', "#{SecureRandom.hex}_#{uploaded_io.original_filename}")

    File.open(save_path, 'wb') do |file|
      file.write(uploaded_io.read)
    end

    begin
      TvShow.import_from_file(save_path, current_user)

      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Discs were successfully imported.' }
      end
    rescue Exception => e
      respond_to do |format|
        format.html { redirect_to root_path, alert: "Discs failed to be imported with error #{perform_import_error_message(e)}." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tv_show_params
      params.require(:tv_show).permit(:name, :tvdb_id, :language, :user_id)
    end

    def perform_import_error_message(exception)
      case exception
        when ActiveRecord::RecordInvalid
          "#{exception.message}: #{exception.record}"
        else
          exception.message
      end
    end
end

src/app/helpers/api/v1/tv_shows_helper.rb
module API::V1::TvShowsHelper
end

src/app/helpers/tv_shows_helper.rb
module TvShowsHelper
  def valid_import_formats
    (TvShow::IMPORT_FORMATS.map { |f| f[:extentions] }).flatten
  end

  def valid_import_formats_mime
    (TvShow::IMPORT_FORMATS.map { |f| f[:mime_type] }).flatten
  end
end

src/app/views/tv_shows/_form.html.erb
<%= form_for(@tv_show) do |f| %>
  <% if @tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
      <% @tv_show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tvdb_id %><br>
    <%= f.text_field :tvdb_id %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="actions">
    <%= f.submit "#{t('general.update')} #{t('tv_shows.tv_show')}" %>
  </div>
<% end %>

src/app/views/tv_shows/_import_form.html.erb
<%= form_tag({action: :perform_import}, multipart: true) do %>
    <div class="field">
      <%= label_tag :file, t('tv_shows.tv_show_file') %>
      <%= file_field_tag 'file', accept: valid_import_formats_mime %> (<%= t('tv_shows.valid_import_formats') %>: <%= valid_import_formats.join(', ') %>)
    </div>
    <div class="actions">
      <%= submit_tag t('tv_shows.import_tv_show') %>
    </div>
<% end %>

src/app/views/tv_shows/_tv_show.html.erb
<tr>
  <td><%= link_to tv_show.name, tv_show %></td>
  <td><%= link_to tv_show.collections.count, tv_show_collections_path(tv_show) %></td>
  <td><%= link_to tv_show.seasons.count, tv_show_seasons_path(tv_show) %></td>
  <td><%= link_to tv_show.episodes.count, tv_show_episodes_path(tv_show) %></td>
  <td><%= tv_show.tvdb_id ? link_to(tv_show.tvdb_id, tvdb_url(tv_show)) : nil %></td>
  <td><%= tv_show.language %></td>
  <td>
    <%= link_to t('tv_shows.export_to_yaml'), export_tv_show_path(tv_show, format: :yaml) if can? :export_to_yaml, TvShow %>
    <%= link_to t('general.edit'), edit_tv_show_path(tv_show) if can? :edit, TvShow %>
    <%= link_to t('general.destroy'), tv_show, method: :delete, data: { confirm: t('general.are_you_sure')} if can? :destroy, TvShow %>
  </td>
</tr>

src/app/views/tv_shows/_tv_shows.html.erb
<table id='itv_shows_table' class='data_table'>
  <thead>
  <tr>
    <th><%= t('tv_shows.name') %></th>
    <th><%= t('collections.collections') %></th>
    <th><%= t('seasons.seasons') %></th>
    <th><%= t('episodes.episodes') %></th>
    <th><%= t('tv_shows.tvdb_id') %></th>
    <th><%= t('tv_shows.language') %></th>
    <th><%= t('general.tables.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% tv_shows.each do |tv_show| %>
    <%= render 'tv_show', :tv_show => tv_show %>
  <% end %>
  </tbody>
</table>

src/app/views/tv_shows/edit.html.erb
<h1><%= t('general.editing') % t('tv_shows.tv_show') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', tv_shows_path %>

src/app/views/tv_shows/import.html.erb
<h1><%= "Import TV Show" %></h1>

<%= render 'import_form' %>
<br />
<br />
<%= link_to 'Back', :back %>

src/app/views/tv_shows/index.html.erb
<h1><%= t('general.listing') % t('tv_shows.tv_shows') %>
  <span class='actions'>
        <% if can? :create, TvShow  %>
          <%= link_to 'New', new_tv_show_path, :id => 'new_tv_show_link' %>
        <% end  %>
    </span>
</h1>
<%= render 'tv_shows', :tv_shows => @tv_shows %>
<br />
<br />
<% if can?(:manage, [TvShow, Disc, Season, Episode, EpisodeDisc]) %>
    <%= link_to t('tv_shows.import_from_yaml'), import_tv_shows_path %>
<% end %>

src/app/views/tv_shows/new.html.erb
<h1><%= t('general.editing') % t('tv_shows.tv_show') %></h1>

<%= render 'form' %>

<%= link_to 'Back', tv_shows_path %>

src/app/views/tv_shows/show.html.erb
<h1><%= @tv_show.name %></h1>

<p>
  <strong><%= t('tv_shows.tvdb_id') %>:</strong>
  <%= link_to @tv_show.tvdb_id, tvdb_url(@tv_show) %>
</p>

<p>
  <strong><%= t('tv_shows.language') %>:</strong>
  <%= @tv_show.language %>
</p>

<h3><%= t('collections.collections') %>
  <span class='actions'>
        <% if can? :create, Collection %>
          <%= link_to 'New', new_tv_show_collection_path(@tv_show), :id => 'new_collection_link' %>
        <% end  %>
  </span>
</h3>
<%= render 'collections/collections', :collections => @tv_show.collections %>
<br />
<h3><%= t('seasons.seasons') %>
  <span class='actions'>
        <% if can? :create, Season %>
          <%= link_to 'New', new_tv_show_season_path(@tv_show), :id => 'new_tv_show_link' %>
        <% end  %>
  </span>
</h3>
<%= render 'seasons/seasons', :seasons => @tv_show.seasons %>
<br />
<h3><%= t('discs.discs') %></h3>
<%= render 'discs/discs', :discs => @tv_show.discs %>
<br />
<h3><%= t('episodes.episodes') %></h3>
<%= render 'episodes/episodes', :episodes => @tv_show.episodes %>
<br />
<br />
<%= link_to t('general.back'), tv_shows_path %>
<% if can?(:edit, TvShow) %>
    | <%= link_to 'Edit', edit_tv_show_path(@tv_show) %>
<% end %>