src/config/routes.rb
Rails.application.routes.draw do
  resources :tv_shows do
    member do
      get :export, :defaults => { :format => :yaml }
    end

    collection do
      get :import
      post :perform_import
    end

    resources :episodes, only: [:index, :show]
    resources :seasons do
      resources :discs do
        resources :episodes, only: [:index, :show]
      end
      resources :episodes do
        resources :episode_discs
      end
    end

    resources :collections do
      resources :discs, only: [:index, :show]

      member do
        get :associate_disc
        post :perform_associate_disc
      end
    end
  end

  root :to => 'tv_shows#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resource :users, only: [:show] do
    resources :api_keys
  end

  namespace :admin do
    get '/' => 'admin#index'
    resources :users
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api, only: [:index, :show]

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :tv_shows do
        collection do
          get :import
        end

        resources :episodes, only: [:index, :show]
        resources :seasons do
          resources :discs do
            resources :episodes, only: [:index, :show]
          end
          resources :episodes do
            resources :episode_discs
          end
        end

        resources :collections do
          resources :discs, only: [:index, :show]

          member do
            post :associate_disc
          end
        end
      end
      resources :discs, only: [:index, :show]
    end
  end
end

src/app/models/collection.rb
class Collection < ActiveRecord::Base
  include Filterable
  extend FriendlyId
  friendly_id :name, use: :slugged

  audited

  has_many :disc_collection, :dependent => :destroy
  has_many :discs, through: :disc_collection

  belongs_to :tv_show
  belongs_to :user

  validates :name, presence: true,
                   uniqueness: true

  def to_s
    self.name
  end

  def to_hash
    {
        name: self.name,
        description: self.description,
        region_code: self.region_code,
        region_name: self.region_name,
    }
  end

  def to_param
    self.name
  end
end

src/app/controllers/api/v1/collections_controller.rb
class API::V1::CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :associate_disc]
  before_action :set_tv_show, only: [:index, :destroy, :associate_disc]

  # GET /collections
  def index
    @collections = @tv_show.collections
  end

  # GET /collections/1
  def show
  end

  # GET /collections/new
  def new
    @collection = @tv_show.collections.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  def create
    @collection = @tv_show.collections.new(collection_params)

    @collection.user = current_user

    respond_to do |format|
      if @collection.save
        format.html { redirect_to [@collection.tv_show, @collection], notice: 'Collection was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /collections/1
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to [@collection.tv_show, @collection], notice: 'Collection was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to tv_show_path(@tv_show), notice: 'Collection was successfully destroyed.' }
    end
  end

  # GET /collections/1/associate_disc
  def associate_disc
  end

  # GET /collections/1/perform_associate_disc
  def perform_associate_disc
    @collection.discs = Disc.find(params[:discs])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to [@collection.tv_show, @collection], notice: 'Discs were successfully associated.' }
      else
        format.html { render :associate_disc }
      end

    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.find_by_tv_show_id_and_name(TvShow.friendly.find(params[:tv_show_id]), params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def collection_params
    params.require(:collection).permit(:disc_collection_id, :name, :description, :region_code, :region_name)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_tv_show
    @tv_show = TvShow.friendly.find(params[:tv_show_id])
  end
end

src/app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :associate_disc, :perform_associate_disc]
  before_action :set_tv_show, only: [:index, :new, :create, :destroy, :associate_disc, :perform_associate_disc]

  # GET /collections
  def index
    @collections = @tv_show.collections
  end

  # GET /collections/1
  def show
  end

  # GET /collections/new
  def new
    @collection = @tv_show.collections.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  def create
    @collection = @tv_show.collections.new(collection_params)

    @collection.user = current_user

    respond_to do |format|
      if @collection.save
        format.html { redirect_to [@collection.tv_show, @collection], notice: 'Collection was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /collections/1
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to [@collection.tv_show, @collection], notice: 'Collection was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to tv_show_path(@tv_show), notice: 'Collection was successfully destroyed.' }
    end
  end

  # GET /collections/1/associate_disc
  def associate_disc
  end

  # GET /collections/1/perform_associate_disc
  def perform_associate_disc
    @collection.discs = Disc.find(params[:discs])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to [@collection.tv_show, @collection], notice: 'Discs were successfully associated.' }
      else
        format.html { render :associate_disc }
      end

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find_by_tv_show_id_and_name(TvShow.friendly.find(params[:tv_show_id]), params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:disc_collection_id, :name, :description, :region_code, :region_name)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.friendly.find(params[:tv_show_id])
    end
end

src/app/helpers/api/v1/collections_helper.rb
module API::V1::CollectionsHelper
end

src/app/helpers/collections_helper.rb
module CollectionsHelper
end

src/app/views/collections/_associate_disc_form.html.erb
<%= form_tag({action: :perform_associate_disc}) do %>
    <div class="field">
      <%= label_tag :discs, t('discs.discs') %>
      <%= select_tag  'discs[]', options_from_collection_for_select(@tv_show.discs, :id, :disc_label, @collection.discs.map(&:id)), multiple: true %>
    </div>

    <div class="actions">
      <%= submit_tag t('collections.associate_discs') %>
    </div>
<% end %>

src/app/views/collections/_collection.html.erb
<tr>
  <td><%= link_to collection.name, tv_show_collection_path(collection.tv_show, collection) %></td>
  <td><%= collection.region_name %></td>
  <td><%= collection.region_code %></td>
  <td><%= link_to collection.discs.count, tv_show_collection_discs_path(collection.tv_show, collection) %></td>
  <td><%= collection.tv_show %></td>
  <td>
    <%= link_to 'Edit', edit_tv_show_collection_path(collection.tv_show, collection) if can? :edit, Collection %>
    <%= link_to 'Destroy', [collection.tv_show, collection], method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, Collection %>
  </td>
</tr>

src/app/views/collections/_collections.html.erb
<table id='collections_table' class='data_table'>
  <thead>
  <tr>
    <th><%= t('collections.name') %></th>
    <th><%= t('collections.region_name') %></th>
    <th><%= t('collections.region_code') %></th>
    <th><%= t('discs.discs') %></th>
    <th><%= t('tv_shows.tv_show') %></th>
    <th><%= t('general.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% collections.each do |collection| %>
      <%= render 'collections/collection', :collection => collection %>
  <% end %>
  </tbody>
</table>

src/app/views/collections/_form.html.erb
<%= form_for([@collection.tv_show, @collection]) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :region_code %><br>
    <%= f.text_field :region_code %>
  </div>
  <div class="field">
    <%= f.label :region_name %><br>
    <%= f.text_field :region_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/collections/associate_disc.html.erb
<h1><%= "Associate with Discs" %></h1>

<%= render 'associate_disc_form' %>
<br />
<br />
<%= link_to 'Back', :back %>

src/app/views/collections/edit.html.erb
<h1><%= t('general.editing') % t('collections.collection') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', :back %>

src/app/views/collections/index.html.erb
<h1><%= t('general.listing') % t('collections.collections') %>
  <span class='actions'>
        <% if can? :create, Collection  %>
          <%= link_to 'New', new_tv_show_collection_path(@tv_show), :id => 'new_collection_link' %>
        <% end %>
    </span>
</h1>

<%= render 'collections/collections', :collections => @collections %>

src/app/views/collections/new.html.erb
<h1><%= t('general.new') % t('collections.collection') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', :back %>

src/app/views/collections/show.html.erb
<h1><%= "#{@collection.tv_show.name} - #{@collection.name}" %></h1>

<p>
  <strong>Name:</strong>
  <%= @collection.name %><br />

  <strong>Description:</strong>
  <%= @collection.description %><br />

  <strong>Region code:</strong>
  <%= @collection.region_code %><br />

  <strong>Region name:</strong>
  <%= @collection.region_name %><br />
</p>

<h3><%= t('discs.discs') %>
  <span class='actions'>
        <% if can? :associate_disc, Disc  %>
          <%= link_to t('collections.associate_discs'), associate_disc_tv_show_collection_path(@collection.tv_show, @collection), :id => 'associate_disc_link' %>
        <% end  %>
    </span>
</h3>
<%= render 'discs/discs', :discs => @collection.discs %>
<br />
<br />
<%= link_to 'Edit', edit_tv_show_collection_path(@collection.tv_show, @collection) %> |
<%= link_to 'Back', tv_show_collection_path(@collection.tv_show, @collection) %>